### ISSUE TITLE
The Starlark Language Server server crashed

### ISSUE THREAD

**Issue by JalonWong** [stackb/bazel-stack-vscode#118] opened 2022-07-22 02:15 UTC
I opened two VSCode windows at the same time and got crash.

- Windows 10
- VSCode 1.69.2
- bazel-stack-vscode 1.9.0
- bazel-stack-vscode-cc 1.2.0

Window 1 output of the Starlark Language Server:
```
time="2022-07-22T10:15:46+08:00" level=info msg="Starlark Language server v1.4.8 (2022-07-22)"
time="2022-07-22T10:15:46+08:00" level=info msg="GoPackagesDriver server listening on grpc://localhost:10021" svc=gpd
time="2022-07-22T10:15:47+08:00" level=info msg="Server Initialized: cwd="
```

Window 2 output of the Starlark Language Server:
```
time="2022-07-22T10:15:57+08:00" level=info msg="Starlark Language server v1.4.8 (2022-07-22)"
time="2022-07-22T10:15:57+08:00" level=info msg="GoPackagesDriver server listening on grpc://localhost:10021" svc=gpd
time="2022-07-22T10:15:57+08:00" level=fatal msg="gopackagesdriver server error: could not create grpc listener: listen tcp 127.0.0.1:10021: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted." svc=gpd
[Info  - 10:15:57] Connection to server got closed. Server will restart.
```

**Comment by pcj** [comment] 2022-07-29 20:42
Duplicate of #113

**Closed by pcj** 2022-07-29 20:42 UTC
